# Generated by Django 4.0.4 on 2022-04-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraires', '0005_alter_itineraire_base_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('mod_status', models.CharField(choices=[('PU', 'Public'), ('PR', 'Privé'), ('HI', 'Caché')], default='PU', max_length=2, verbose_name='Visibilité du commentaire')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.sortie', verbose_name='Sortie')),
            ],
        ),
    ]
