# Generated by Django 4.0.4 on 2022-05-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0006_itineraire_arriv_lat_itineraire_arriv_lon_and_more'),
        ('itineraires', '0010_alter_photo_image'),
    ]

    operations = [
    ]
