# Generated by Django 4.0.4 on 2022-05-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0011_merge_20220504_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Localisation')),
                ('lat_loc', models.FloatField(default=43.5695, verbose_name='Longitude de la localisation')),
                ('long_loc', models.FloatField(default=1.4728, verbose_name='Longitude de la localisation')),
            ],
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='arriv_lat',
            field=models.FloatField(default=43.5667, verbose_name="Longitude du point d'arrivée"),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='arriv_lon',
            field=models.FloatField(default=1.4748, verbose_name="Longitude du point d'arrivée"),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='start_lat',
            field=models.FloatField(default=43.5695, verbose_name='Longitude du point de départ'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='start_lon',
            field=models.FloatField(default=1.4728, verbose_name='Longitude du point de départ'),
        ),
    ]
