# Generated by Django 4.0.4 on 2022-05-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0012_alter_itineraire_arriv_lat_and_more'),
        ('itineraires', '0012_localisation_alter_itineraire_arriv_lat_and_more'),
    ]

    operations = [
    ]
